name: Homebrew

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Bump Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.PAT }}
          formula: ai-code-arc
